apiVersion: v1
kind: Pod
metadata:
  name: pvc-access-container
  namespace: kubeflow-seldon
spec:
  containers:
  - name: pvc-access-container
    image: busybox
    command: ["/bin/sh", "-ec", "sleep 1000"]
    volumeMounts:
    - name: mypvc
      mountPath: /mnt
  volumes:
  - name: mypvc
    persistentVolumeClaim:
      claimName: PVC_NAME
